logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: :9997

rtsp: yes
rtspAddress: :8554
protocols: [tcp, udp]

hls: yes
hlsAddress: :8888

webrtc: yes
webrtcAddress: :8889

rtmp: yes
rtmpAddress: :1935

paths:
  all_others:
    source: publisher
    runOnReady: >
      curl -s -X POST "http://backend:8000/api/streams/webhook/ready?path=$MTX_PATH"
    runOnReadyRestart: no
    runOnNotReady: >
      curl -s -X POST "http://backend:8000/api/streams/webhook/not-ready?path=$MTX_PATH"
